openapi: 3.0.0
servers:
  - description: "SwaggerHub API Auto Mocking"
    url: https://virtserver.swaggerhub.com/VNGRealisatie/api/bevragingen_ingeschreven_personen/v1
  - description: "Referentie-implementatie"
    url: https://www.voorbeeldgemeente.nl/api/bevragingen_ingeschreven_personen/v1
info:
  title: Bevragingen ingeschreven personen
  description: "API voor het ontsluiten van gegevens van ingeschreven personen en aanverwante gegevens uit de GBA en RNI. Met deze API worden de actuele gegevens van ingeschreven personen, hun kinderen, partners en ouders ontsloten. Ook de gegevens over reisdocumenten worden via deze API ontsloten. Zie de [Functionele documentatie](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/tree/master/features) voor nadere toelichting."
  version: "1.0"
  contact:
    url: https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen
  license:
    name: European Union Public License, version 1.2 (EUPL-1.2)
    url: https://eupl.eu/1.2/nl/
paths:
  /ingeschrevenpersonen:
    get:
      responses:
        '200':
          description: "Zoekactie geslaagd"
          headers:
            api-version:
              $ref: "https://raw.githubusercontent.com/MelvLee/OpenAPI-Sandbox/master/headers.yaml#/components/headers/api_version"
            warning:
              $ref: "https://raw.githubusercontent.com/MelvLee/OpenAPI-Sandbox/master/headers.yaml#/components/headers/warning"
            X-Rate-Limit-Limit:
              $ref: "https://raw.githubusercontent.com/MelvLee/OpenAPI-Sandbox/master/headers.yaml#/components/headers/X-RateLimit-Limit"
            X-Rate-Limit-Remaining:
              $ref: "https://raw.githubusercontent.com/MelvLee/OpenAPI-Sandbox/master/headers.yaml#/components/headers/X-RateLimit-Remaining"
            X-Rate-Limit-Reset:
              $ref: "https://raw.githubusercontent.com/MelvLee/OpenAPI-Sandbox/master/headers.yaml#/components/headers/X-RateLimit-Reset"
          content:
            application/hal+json:
              schema:
                type: object
                properties:
                  _links:
                    $ref: "https://raw.githubusercontent.com/MelvLee/OpenAPI-Sandbox/master/components.yaml#/components/schemas/HalCollectionLinks"
                  _embedded:
                    type: object
                    properties:
                      ingeschrevenpersonen:
                        type: array
                        items:
                          $ref: '#/components/schemas/IngeschrevenPersoon'
components:
  schemas:
    IngeschrevenPersoon:
      type: "object"
      description: "Categorie 01/51 Gegevens over de ingeschrevene."
      properties:
        aktenummer:
          type: "string"
          title: "aktenummer"
          description: "Element 81.20 Een aanduiding van de akte die is opgenomen\
            \ in de registers van de burgerlijke stand in Nederland. De eerste drie\
            \ posities van het aktenummer dienen conform [Tabel 39,Tabel Akteaanduiding](https://publicaties.rvig.nl/dsresource?objectid=4796&amp;type=org)\
            \ te zijn. De laatste 4 posities bevatten een volgnummer van de akte."
          maxLength: 7
        burgerservicenummer:
          type: "string"
          title: "Burgerservicenummer"
          description: "Het burgerservicenummer, bedoeld in artikel 1.1 van de Wet\
            \ algemene bepalingen burgerservicenummer. Element 01.20 Het burgerservicenummer,\
            \ bedoeld in artikel 1.1 van de Wet algemene bepalingen burgerservicenummer.\
            \ Alle nummers waarvoor geldt dat, indien aangeduid als (s0 s1 s2 s3 s4\
            \ s5 s6 s7 s8), het resultaat van (9*s0) + (8*s1) + (7*s2) +...+ (2*s7)\
            \ - (1*s8) deelbaar is door elf. Er moeten dus 9 cijfers aanwezig zijn."
          pattern: "^[0-9]{9}$"
          maxLength: 9
          minLength: 9
          example: "555555021"
