openapi: 3.0.0

components:
  headers:
    api_version:
      description: Geeft een specifieke API-versie aan in de context van een specifieke aanroep.
      schema:
        type: integer
      example: 1.0.1

    warning:
      description: 'zie RFC 7234. In het geval een major versie wordt uitgefaseerd, gebruiken we warn-code 299 ("Miscellaneous Persistent Warning") en het API end-point (inclusief versienummer) als de warn-agent van de warning, gevolgd door de warn-text met de human-readable waarschuwing'
      schema:
        type: string
      example: '299 https://service.../api/.../v1 "Deze versie van de API is verouderd en zal uit dienst worden genomen op 2018-02-01. Raadpleeg voor meer informatie hier de documentatie: https://omgevingswet.../api/.../v1".'

    X-RateLimit-Limit:
      description: The maximum number of requests you're permitted to make per hour.
      schema:
        type: integer
      example: 100

    X-RateLimit-Remaining:
      description: The number of requests remaining in the current rate limit window.
      schema:
        type: integer
      example: 94

    X-RateLimit-Reset:
      description: The time at which the current rate limit window resets in UTC epoch seconds.
      schema:
        type: integer

    X-Pagination-Page:
      description: Huidige pagina.
      required: True
      schema:
        type: integer
      example: 3

    X-Pagination-Limit:
      description: Aantal resultaten per pagina.
      required: true
      schema:
        type: integer
      example: 20

    Crs:
      schema:
        type: string
        enum:
          - "EPSG:4326"
          - "EPSG:4258"
          - "EPSG:28992"
        description: >
          Het gekozen coördinatenstelsel (CRS):
          * `EPSG:4326` - WGS84, Wereld
          * `EPSG:4258` - ETRS89, Europees
          * `EPSG:28992` - RD, Nederlands
