openapi: 3.0.0
components:
  responses:
    BadRequestResponse:
      description: Bad Request
      headers:
        api-version:
          $ref: "https://raw.githubusercontent.com/MelvLee/OpenAPI-Sandbox/master/headers.yaml#/components/headers/api_version"
      content:
        application/problem+json:
          schema:
            $ref: "https://raw.githubusercontent.com/MelvLee/OpenAPI-Sandbox/master/components.yaml#/components/schemas/ValidatieFoutbericht"
    UnauthorizedResponse:
      description: Unauthorized
      headers:
        api-version:
         $ref: "https://raw.githubusercontent.com/MelvLee/OpenAPI-Sandbox/master/headers.yaml#/components/headers/api_version"
      content:
        application/problem+json:
          schema:
            $ref: "https://raw.githubusercontent.com/MelvLee/OpenAPI-Sandbox/master/components.yaml#/components/schemas/Foutbericht"
    ForbiddenResponse:
      description: Forbidden
      headers:
        api-version:
          $ref: "https://raw.githubusercontent.com/MelvLee/OpenAPI-Sandbox/master/headers.yaml#/components/headers/api_version"
      content:
        application/problem+json:
          schema:
            $ref: "https://raw.githubusercontent.com/MelvLee/OpenAPI-Sandbox/master/components.yaml#/components/schemas/Foutbericht"
